package wk5;

/**
 * This is a cool project that my prof decided to do because he loves pizza
 * However, I am learning so mush. The downside is that now I want to eat pizza
 *
 * @author Ben Blanc
 * @since 2024-02-06
 * @version 1.0
 * @implNote This is now you implement this class
 */
public class PizzaOrder {

    /** Comma separated values representing the toppings of a pizza */
    String toppings;
    private int numberOfSlices = 4;
    private final double pricePerSlice = 2.25;

    private int numberOfToppings;
    private int timeToPrepare = 10;

    private double price;

    public PizzaOrder(){}

    /**
     * Returns the price of the pizza order
     * @return price of the pizza order as a double
     */
    public double getPrice() {
        return price;
    }

    /**
     * Get the price of the order after applying the discount based on the category of person
     * @param category a string that only accepts limited values (students and elderly)
     * @return the discount price of the pizza order
     */
    public double getPrice(String category){
        double calculatedPrice = getPrice();
        if(category.toLowerCase().contains("student")){
            calculatedPrice = getPrice() * .8;
        }
        else if(category.toLowerCase().contains("elder")){
            calculatedPrice = getPrice() / 2;
        }
        return calculatedPrice;
    }

    // forward slash + two asterisks

    /**
     * The price is generated by multiplying the number of slices by the price per slice
     */
    public void setPrice() {
       price =  numberOfSlices * pricePerSlice;
    }

    /**
     * time the client should expect their pizza
     * @return time until pizza is delivered
     */
    public int getTimeToPrepare() {
        return timeToPrepare;
    }

    /**
     * Calculate the time based on the number of slices and the number of toppings
     */
    public void setTimeToPrepare() {
        timeToPrepare += numberOfSlices + numberOfToppings;
    }
}
